spring.application.name=ai-code-assistant

server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_db
spring.datasource.username=postgres
spring.datasource.password=Sushma@12345

# Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Actuator Health Endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always